### ISSUE TITLE
typo in the first string declaration

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/objc-speaking-grandma#3]
User: David Gabeau

Batch: 001

Current Lesson: Conditionals

Location: https://learn.co/tracks/mobile-development-with-ios/objective-c-basics/basic-objective-c/code-along-speaking-grandma?track_id=6646&batch_id=108

Bug Description: Very small error: The first string declaration for NSString *talkToGrandma = @"Hi, Grandma."; has a period. In code-along 2 the string does not have a period. This was slightly confusing since I'm looking out for small syntax errors. But I'm not sure if it matters.

**Comment by markedwardmurray** [comment]
Thanks Kaitlin. Does he not know about the "edit" feature?

**Comment by kvignali** [comment]
we alerted him, but I wasn't 100% sure if this was a real typo so I dropped it in here

**Comment by markedwardmurray** [comment]
There aren't any tests with this lab so it won't make a difference, but I'll fix the punctuation. I noticed a couple of other inconsistencies also.
